package com.paloit.entities;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Convocation generated by hbm2java
 */
@Entity
@Table(name = "convocation", schema = "public")
public class Convocation implements java.io.Serializable {

	private ConvocationId id;

	public Convocation() {
	}

	public Convocation(ConvocationId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idMatch", column = @Column(name = "id_match", nullable = false)),
			@AttributeOverride(name = "idJoueur", column = @Column(name = "id_joueur", nullable = false)) })
	public ConvocationId getId() {
		return this.id;
	}

	public void setId(ConvocationId id) {
		this.id = id;
	}

}
