package com.paloit.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * ConvocationId generated by hbm2java
 */
@Embeddable
public class ConvocationId implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private int idMatch;
	private int idJoueur;

	public ConvocationId() {
	}

	public ConvocationId(int idMatch, int idJoueur) {
		this.idMatch = idMatch;
		this.idJoueur = idJoueur;
	}

	@Column(name = "id_match", nullable = false)
	public int getIdMatch() {
		return this.idMatch;
	}

	public void setIdMatch(int idMatch) {
		this.idMatch = idMatch;
	}

	@Column(name = "id_joueur", nullable = false)
	public int getIdJoueur() {
		return this.idJoueur;
	}

	public void setIdJoueur(int idJoueur) {
		this.idJoueur = idJoueur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof ConvocationId))
			return false;
		ConvocationId castOther = (ConvocationId) other;

		return (this.getIdMatch() == castOther.getIdMatch())
				&& (this.getIdJoueur() == castOther.getIdJoueur());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdMatch();
		result = 37 * result + this.getIdJoueur();
		return result;
	}

}
