package com.paloit.entities;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

import org.hibernate.annotations.GenericGenerator;

/**
 * Educateur generated by hbm2java
 */
@Entity
@Table(name = "educateur", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "login_educateur"))
public class Educateur implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 10L;
	private int idEducateur;
	private Equipe equipe;
	private String fonction;
	private String loginEducateur;
	private String mailEducateur;
	private String mdpEducateur;
	private String nomEducateur;
	private String prenomEducateur;
	private String telEducateur;
	private boolean enabled;
	private Set<Roles> roleses = new HashSet<Roles>(0);
	private Set<Match> matches = new HashSet<Match>(0);
	private Set<Entrainement> entrainements = new HashSet<Entrainement>(0);

	public Educateur() {
	}

	public Educateur(int idEducateur, Equipe equipe, boolean enabled) {
		this.idEducateur = idEducateur;
		this.equipe = equipe;
		this.enabled = enabled;
	}

	public Educateur(int idEducateur, Equipe equipe, String fonction,
			String loginEducateur, String mailEducateur, String mdpEducateur,
			String nomEducateur, String prenomEducateur, String telEducateur,
			boolean enabled, Set<Roles> roleses, Set<Match> matches,
			Set<Entrainement> entrainements) {
		this.idEducateur = idEducateur;
		this.equipe = equipe;
		this.fonction = fonction;
		this.loginEducateur = loginEducateur;
		this.mailEducateur = mailEducateur;
		this.mdpEducateur = mdpEducateur;
		this.nomEducateur = nomEducateur;
		this.prenomEducateur = prenomEducateur;
		this.telEducateur = telEducateur;
		this.enabled = true;
		this.roleses = roleses;
		this.matches = matches;
		this.entrainements = entrainements;
	}

	@Id
	@GenericGenerator(name="kaugen" , strategy="increment")
    @GeneratedValue(generator="kaugen")
	@Column(name = "id_educateur", unique = true, nullable = false)
	public int getIdEducateur() {
		return this.idEducateur;
	}

	public void setIdEducateur(int idEducateur) {
		this.idEducateur = idEducateur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_equipe", nullable = false)
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@Column(name = "fonction")
	public String getFonction() {
		return this.fonction;
	}

	public void setFonction(String fonction) {
		this.fonction = fonction;
	}

	@Column(name = "login_educateur", unique = true)
	public String getLoginEducateur() {
		return this.loginEducateur;
	}

	public void setLoginEducateur(String loginEducateur) {
		this.loginEducateur = loginEducateur;
	}

	@Column(name = "mail_educateur")
	public String getMailEducateur() {
		return this.mailEducateur;
	}

	public void setMailEducateur(String mailEducateur) {
		this.mailEducateur = mailEducateur;
	}

	@Column(name = "mdp_educateur")
	public String getMdpEducateur() {
		return this.mdpEducateur;
	}

	public void setMdpEducateur(String mdpEducateur) {
		this.mdpEducateur = mdpEducateur;
	}

	@Column(name = "nom_educateur")
	public String getNomEducateur() {
		return this.nomEducateur;
	}

	public void setNomEducateur(String nomEducateur) {
		this.nomEducateur = nomEducateur;
	}

	@Column(name = "prenom_educateur")
	public String getPrenomEducateur() {
		return this.prenomEducateur;
	}

	public void setPrenomEducateur(String prenomEducateur) {
		this.prenomEducateur = prenomEducateur;
	}

	@Column(name = "tel_educateur")
	public String getTelEducateur() {
		return this.telEducateur;
	}

	public void setTelEducateur(String telEducateur) {
		this.telEducateur = telEducateur;
	}

	@Column(name = "enabled", nullable = false)
	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "educateur")
	public Set<Roles> getRoleses() {
		return this.roleses;
	}

	public void setRoleses(Set<Roles> roleses) {
		this.roleses = roleses;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "educateur")
	public Set<Match> getMatches() {
		return this.matches;
	}

	public void setMatches(Set<Match> matches) {
		this.matches = matches;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "educateur")
	public Set<Entrainement> getEntrainements() {
		return this.entrainements;
	}

	public void setEntrainements(Set<Entrainement> entrainements) {
		this.entrainements = entrainements;
	}

}
