package com.paloit.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Entrainement generated by hbm2java
 */
@Entity
@Table(name = "entrainement", schema = "public")
public class Entrainement implements java.io.Serializable {

	
	private static final long serialVersionUID = 1L;
	private int idEntrainement;
	private Educateur educateur;
	private Date dateEntrainement;
	private String lieuEntrainement;

	public Entrainement() {
	}

	public Entrainement(int idEntrainement, Educateur educateur) {
		this.idEntrainement = idEntrainement;
		this.educateur = educateur;
	}

	public Entrainement(int idEntrainement, Educateur educateur,
			Date dateEntrainement, String lieuEntrainement) {
		this.idEntrainement = idEntrainement;
		this.educateur = educateur;
		this.dateEntrainement = dateEntrainement;
		this.lieuEntrainement = lieuEntrainement;
	}

	@Id
	@GenericGenerator(name="kaugen" , strategy="increment")
    @GeneratedValue(generator="kaugen")
	@Column(name = "id_entrainement", unique = true, nullable = false)
	public int getIdEntrainement() {
		return this.idEntrainement;
	}

	public void setIdEntrainement(int idEntrainement) {
		this.idEntrainement = idEntrainement;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_educateur", nullable = false)
	public Educateur getEducateur() {
		return this.educateur;
	}

	public void setEducateur(Educateur educateur) {
		this.educateur = educateur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_entrainement", length = 13)
	public Date getDateEntrainement() {
		return this.dateEntrainement;
	}

	public void setDateEntrainement(Date dateEntrainement) {
		this.dateEntrainement = dateEntrainement;
	}

	@Column(name = "lieu_entrainement")
	public String getLieuEntrainement() {
		return this.lieuEntrainement;
	}

	public void setLieuEntrainement(String lieuEntrainement) {
		this.lieuEntrainement = lieuEntrainement;
	}

}
