package com.paloit.entities;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Equipe generated by hbm2java
 */
@Entity
@Table(name = "equipe", schema = "public")
public class Equipe implements java.io.Serializable {

	private int idEquipe;
	private String categorie;
	private String classe;
	private Set<Educateur> educateurs = new HashSet<Educateur>(0);
	private Set<Joueur> joueurs = new HashSet<Joueur>(0);

	public Equipe() {
	}

	public Equipe(int idEquipe) {
		this.idEquipe = idEquipe;
	}

	public Equipe(int idEquipe, String categorie, String classe,
			Set<Educateur> educateurs, Set<Joueur> joueurs) {
		this.idEquipe = idEquipe;
		this.categorie = categorie;
		this.classe = classe;
		this.educateurs = educateurs;
		this.joueurs = joueurs;
	}

	@Id
	@GenericGenerator(name="kaugen" , strategy="increment")
    @GeneratedValue(generator="kaugen")
	@Column(name = "id_equipe", unique = true, nullable = false)
	public int getIdEquipe() {
		return this.idEquipe;
	}

	public void setIdEquipe(int idEquipe) {
		this.idEquipe = idEquipe;
	}

	@Column(name = "categorie")
	public String getCategorie() {
		return this.categorie;
	}

	public void setCategorie(String categorie) {
		this.categorie = categorie;
	}

	@Column(name = "classe")
	public String getClasse() {
		return this.classe;
	}

	public void setClasse(String classe) {
		this.classe = classe;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "equipe")
	public Set<Educateur> getEducateurs() {
		return this.educateurs;
	}

	public void setEducateurs(Set<Educateur> educateurs) {
		this.educateurs = educateurs;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "equipe")
	public Set<Joueur> getJoueurs() {
		return this.joueurs;
	}

	public void setJoueurs(Set<Joueur> joueurs) {
		this.joueurs = joueurs;
	}

}
