package com.paloit.entities;

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Joueur generated by hbm2java
 */
@Entity
@Table(name = "joueur", schema = "public")
public class Joueur implements java.io.Serializable {

	private int idJoueur;
	private Equipe equipe;
	private String adresseJoueur;
	private Date datenaissanceJoueur;
	private String nomJoueur;
	private String prenomJoueur;
	private String telJoueur;

	public Joueur() {
	}

	public Joueur(int idJoueur, Equipe equipe) {
		this.idJoueur = idJoueur;
		this.equipe = equipe;
	}

	public Joueur(int idJoueur, Equipe equipe, String adresseJoueur,
			Date datenaissanceJoueur, String nomJoueur, String prenomJoueur,
			String telJoueur) {
		this.idJoueur = idJoueur;
		this.equipe = equipe;
		this.adresseJoueur = adresseJoueur;
		this.datenaissanceJoueur = datenaissanceJoueur;
		this.nomJoueur = nomJoueur;
		this.prenomJoueur = prenomJoueur;
		this.telJoueur = telJoueur;
	}

	@Id
	@GenericGenerator(name="kaugen" , strategy="increment")
    @GeneratedValue(generator="kaugen")
	@Column(name = "id_joueur", unique = true, nullable = false)
	public int getIdJoueur() {
		return this.idJoueur;
	}

	public void setIdJoueur(int idJoueur) {
		this.idJoueur = idJoueur;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_equipe", nullable = false)
	public Equipe getEquipe() {
		return this.equipe;
	}

	public void setEquipe(Equipe equipe) {
		this.equipe = equipe;
	}

	@Column(name = "adresse_joueur")
	public String getAdresseJoueur() {
		return this.adresseJoueur;
	}

	public void setAdresseJoueur(String adresseJoueur) {
		this.adresseJoueur = adresseJoueur;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "datenaissance_joueur", length = 13)
	public Date getDatenaissanceJoueur() {
		return this.datenaissanceJoueur;
	}

	public void setDatenaissanceJoueur(Date datenaissanceJoueur) {
		this.datenaissanceJoueur = datenaissanceJoueur;
	}

	@Column(name = "nom_joueur")
	public String getNomJoueur() {
		return this.nomJoueur;
	}

	public void setNomJoueur(String nomJoueur) {
		this.nomJoueur = nomJoueur;
	}

	@Column(name = "prenom_joueur")
	public String getPrenomJoueur() {
		return this.prenomJoueur;
	}

	public void setPrenomJoueur(String prenomJoueur) {
		this.prenomJoueur = prenomJoueur;
	}

	@Column(name = "tel_joueur")
	public String getTelJoueur() {
		return this.telJoueur;
	}

	public void setTelJoueur(String telJoueur) {
		this.telJoueur = telJoueur;
	}

}
