package com.paloit.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * News generated by hbm2java
 */
@Entity
@Table(name = "news", schema = "public")
public class News implements java.io.Serializable {

	private static final long serialVersionUID = 7710031661705901727L;
	private int idNews;
	private byte[] imageNews;
	private String texteNews;
	private String titreNews;

	public News() {
	}

	public News(int idNews) {
		this.idNews = idNews;
	}

	public News(int idNews, byte[] imageNews, String texteNews, String titreNews) {
		this.idNews = idNews;
		this.imageNews = imageNews;
		this.texteNews = texteNews;
		this.titreNews = titreNews;
	}

	@Id
	@GenericGenerator(name="kaugen" , strategy="increment")
    @GeneratedValue(generator="kaugen")
	@Column(name = "id_news", unique = true, nullable = false)
	public int getIdNews() {
		return this.idNews;
	}

	public void setIdNews(int idNews) {
		this.idNews = idNews;
	}

	@Column(name = "image_news")
	public byte[] getImageNews() {
		return this.imageNews;
	}

	public void setImageNews(byte[] imageNews) {
		this.imageNews = imageNews;
	}

	@Column(name = "texte_news")
	public String getTexteNews() {
		return this.texteNews;
	}

	public void setTexteNews(String texteNews) {
		this.texteNews = texteNews;
	}

	@Column(name = "titre_news")
	public String getTitreNews() {
		return this.titreNews;
	}

	public void setTitreNews(String titreNews) {
		this.titreNews = titreNews;
	}

}
