package com.paloit.entities;

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * PresenceId generated by hbm2java
 */
@Embeddable
public class PresenceId implements java.io.Serializable {

	
	private static final long serialVersionUID = -8471951889043222378L;
	private int idEntrainement;
	private int idJoueur;

	public PresenceId() {
	}

	public PresenceId(int idEntrainement, int idJoueur) {
		this.idEntrainement = idEntrainement;
		this.idJoueur = idJoueur;
	}

	@Column(name = "id_entrainement", nullable = false)
	public int getIdEntrainement() {
		return this.idEntrainement;
	}

	public void setIdEntrainement(int idEntrainement) {
		this.idEntrainement = idEntrainement;
	}

	@Column(name = "id_joueur", nullable = false)
	public int getIdJoueur() {
		return this.idJoueur;
	}

	public void setIdJoueur(int idJoueur) {
		this.idJoueur = idJoueur;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof PresenceId))
			return false;
		PresenceId castOther = (PresenceId) other;

		return (this.getIdEntrainement() == castOther.getIdEntrainement())
				&& (this.getIdJoueur() == castOther.getIdJoueur());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getIdEntrainement();
		result = 37 * result + this.getIdJoueur();
		return result;
	}

}
