package com.paloit.entities;

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * Presence generated by hbm2java
 */
@Entity
@Table(name = "presence", schema = "public")
public class Presence implements java.io.Serializable {

	private PresenceId id;

	public Presence() {
	}

	public Presence(PresenceId id) {
		this.id = id;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "idEntrainement", column = @Column(name = "id_entrainement", nullable = false)),
			@AttributeOverride(name = "idJoueur", column = @Column(name = "id_joueur", nullable = false)) })
	public PresenceId getId() {
		return this.id;
	}

	public void setId(PresenceId id) {
		this.id = id;
	}

}
